apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - backend
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - frontend
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-debug
  labels:
    app: frontend-debug
spec:
  containers:
  - name: nginx
    image: nginx:latest
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
